### ISSUE TITLE
Add dynamic cluster image 

### ISSUE THREAD

**Issue by mohamed6996** [coletiv/flutter_google_maps_clusters#1]
Great example! however, it devoid of dynamic cluster image. at the time, we show a static image, i want to show an image that changes its color according to the number like [clustering_google_maps ]( https://github.com/giandifra/clustering_google_maps)

**Comment by biklas7** [comment]
@mohamed6996 Hi! Glad you liked the example. Since we need to convert the image into a BitmapDescriptor to use with Google Maps, it's more difficult to have dynamic images working. Maybe we're doing a follow-up article with that. In the meantime, do you have any suggestions on how to achieve that?

**Comment by mohamed6996** [comment]
I have managed to do so. Its very simple! 
Please, follow this thread on stackoverflow [How to change the icon size of Google Maps marker in Flutter?](https://stackoverflow.com/questions/53633404/how-to-change-the-icon-size-of-google-maps-marker-in-flutter)

And here is a snippet of my code: 

```
Future<Uint8List> getBytesFromCanvas(int nodeSize) async {
    final PictureRecorder pictureRecorder = PictureRecorder();
    MaterialColor color = _getColor(nodeSize);
    final Canvas canvas = Canvas(pictureRecorder);
    final Paint paint1 = Paint()..color = color[400];
    final Paint paint2 = Paint()..color = color[300];
    final Paint paint3 = Paint()..color = color[100];
    final int size = 120;
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.0, paint3);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.4, paint2);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 3.3, paint1);
    TextPainter painter = TextPainter(textDirection: TextDirection.ltr);
    painter.text = TextSpan(
      text: nodeSize.toString(),
      style: TextStyle(
          fontSize: size / 4, color: Colors.black, fontWeight: FontWeight.bold),
    );
    painter.layout();
    painter.paint(
      canvas,
      Offset(size / 2 - painter.width / 2, size / 2 - painter.height / 2),
    );

    final img = await pictureRecorder.endRecording().toImage(size, size);
    final data = await img.toByteData(format: ImageByteFormat.png);
    return data.buffer.asUint8List();
  }

  MaterialColor _getColor(int size) {
    MaterialColor color;

    if (size < 10) {
      color = Colors.grey;
    } else if (size < 25) {
      color = Colors.blue;
    } else if (size < 25) {
      color = Colors.blue;
    } else if (size < 50) {
      color = Colors.green;
    } else if (size < 100) {
      color = Colors.yellow;
    } else if (size < 500) {
      color = Colors.orange;
    } else if (size < 1000) {
      color = Colors.red;
    } else {
      color = Colors.pink;
    }

    return color;
  }
```


```
 // Finalize the markers to display on the map.
    Map<MarkerId, Marker> markers = Map();

    for (MapMarker feature in clusters) {
      BitmapDescriptor bitmapDescriptor;

      if (feature.isCluster) {
        final Uint8List markerIcon =
            await getBytesFromCanvas(feature.pointsSize);
        bitmapDescriptor = BitmapDescriptor.fromBytes(markerIcon);
      } else {
        bitmapDescriptor = BitmapDescriptor.defaultMarker;
      }

      var marker = Marker(
          markerId: MarkerId(feature.markerId),
          position: LatLng(feature.latitude, feature.longitude),
          infoWindow: InfoWindow(title: feature.locationName),
          icon: bitmapDescriptor);

      markers.putIfAbsent(MarkerId(feature.markerId), () => marker);
    }

    // Publish markers to subscribers.
    _addMarkers(markers);
```


The method getBytesFromCanvas is from [clustering_google_maps](https://pub.dev/packages/clustering_google_maps)

**Comment by biklas7** [comment]
Thanks! I will check it out and update the example :+1:

**Comment by mohamed6996** [comment]
Thank you @biklas7  for your great support! Keep it up 👍

**Comment by lapadev** [comment]
@mohamed6996, could you provide the whole function where you placed  this: 

>  // Finalize the markers to display on the map.
    Map<MarkerId, Marker> markers = Map();

    for (MapMarker feature in clusters) {
      BitmapDescriptor bitmapDescriptor;

      if (feature.isCluster) {
        final Uint8List markerIcon =
            await getBytesFromCanvas(feature.pointsSize);
        bitmapDescriptor = BitmapDescriptor.fromBytes(markerIcon);
      } else {
        bitmapDescriptor = BitmapDescriptor.defaultMarker;
      }

      var marker = Marker(
          markerId: MarkerId(feature.markerId),
          position: LatLng(feature.latitude, feature.longitude),
          infoWindow: InfoWindow(title: feature.locationName),
          icon: bitmapDescriptor);

      markers.putIfAbsent(MarkerId(feature.markerId), () => marker);
    }

    // Publish markers to subscribers.
    `_addMarkers(markers);`

Or the page/context for this. Please

**Comment by biklas7** [comment]
@mohamed6996 Thanks to your tips on how to do this, I was able to add this feature to the project :+1:  check https://github.com/coletiv/flutter_google_maps_clusters/pull/2
