### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by fpv999** [coletiv/flutter_google_maps_clusters#3]
in map_marker.dart
you should create marker id different way for cluster points, because their IDs can be the same as normal points IDs. That resulted in occasional improper display of points on my map.

````
...

  Marker toMarker() => Marker(
        markerId: MarkerId(isCluster ? "CL_"+id : id),
        position: LatLng(
          position.latitude,
          position.longitude,
        ),
        icon: icon,
      );
}
````

**Comment by biklas7** [comment]
@fpv999 thanks for reporting that :+1: it was fixed on https://github.com/coletiv/flutter_google_maps_clusters/pull/4
