### ISSUE TITLE
future builder google maps marker

### ISSUE THREAD

**Issue by icangku** [coletiv/flutter_google_maps_clusters#7]
i wanna get the marker from future builder, not static, how to make it possible?

**Comment by biklas7** [comment]
I'm afraid that I'm not understanding your question. Can you elaborate a bit?

Thanks

**Comment by icangku** [comment]
in your code you have set the longitude and latitude in a list, but how do i set list of longitude and latitude using future builder?

**Comment by biklas7** [comment]
Where in the code? What are you trying to achieve by using a FutureBuilder?

**Comment by icangku** [comment]
I'm using FutureBuilder because I'm using for infinite scroll list view,

**Comment by biklas7** [comment]
So you want to get a list of markers to use in an infinite scroll list view?

**Comment by icangku** [comment]
no, i'm using future builder because i use it in listview to show my data and in my data there is long, and lat in each data and in the same time i'm using it as infinite scroll, which means my data will be added continously and also the markers

**Comment by biklas7** [comment]
You can create a Future simply by using `Future.value(yourData)`. Then use it in your FutureBuilder. Check https://api.dart.dev/stable/2.1.0/dart-async/Future/Future.value.html and https://stackoverflow.com/a/53853225/6937784
