### ISSUE TITLE
Having issues with image

### ISSUE THREAD

**Issue by datapalace** [coletiv/flutter_google_maps_clusters#9]
You guys have done a great job.
But please Images are not showing. Please help.

**Comment by biklas7** [comment]
Thanks for the words. @datapalace can you detail your problem a bit further? Maybe add some code to reproduce the problem? :thinking:

**Comment by datapalace** [comment]
@biklas7 What i meant was that the custom marker image for the clustered locations is not showing on the map. 

Its the same thing after I tested it using emulator and also using my phone as emulator.

I tried to click on the link to the image of the marker, I could see the image exist, I also tried changing the link of the image to another one. the problem still persist.

What could be the problem?
Is it possible to call the image from assets frolder instead of calling from a http url.

I so much appreciate your response.

Thanks.

**Comment by biklas7** [comment]
Hi @datapalace, should be working now. Thanks for letting me know :+1:
